server.port: 8801

spring:
  config.name: ClientService

  datasource:
    url: jdbc:h2:file:~/ClientService;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #hibernate.ddl-auto: none
    #generate-ddl: false
    #properties.hibernate.hbm2ddl.auto: none