server.port: 8700
spring.application.name: ZuulServer
zuul:
  ignoredServices: '*'
  routes:
    clients:
      path: /client/**
      serviceId: ClientService
      stripPrefix: true
    accounts:
      path: /account/**
      serviceId: AccountService
      stripPrefix: true
    card-processing:
      path: /processing/**
      serviceId: ProcessingService
      stripPrefix: true

